os:
  - linux
sudo: required
language: node_js
node_js:
  - "10.0.0"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop

install:
  - npm install codecov -g
  - npm install -g codeclimate-test-reporter
  - npm install

script:
  - npm test-coverage
  - npm build

after_success:
  - codecov
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_MASTER codeclimate-test-reporter < coverage/lcov.info
  - test $TRAVIS_BRANCH = "develop" && test $TRAVIS_PULL_REQUEST = "false" && CODECLIMATE_API_HOST=$CODECLIMATE_API_HOST CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN_DEVELOP codeclimate-test-reporter < coverage/lcov.info

notifications:
  email:
    on_failure: change
    on_success: change
  slack: quantified-self-io:gWxqdRGo14eo9MoBMtIPX6ME

deploy:
  provider: npm
  email: jimmykane9@gmail.com
  skip_cleanup: true
  api_key:
    secure: qPFEpGo3nVdRaL7m2NGSEIuHTDD1bJH3xBHd+K78lxwI7bBdlKfpM/umrw0BiNGZUOUAUQN2KUYBQrspFGwSr3M+S3w7Rb79xxzPvR5+Y4MfS56LZbipFNFSusDjz5wTrN4RsUoE44O/NqwrCvG2ZGsHlYzn1FCBzKDL6iht88Jdx4R3iFBZgTndRPbPoBsaAuT6cwBp5x8XA4Njlq8pPHRHI8IZ4/bE+/dSZBos7yrtr4tDv/yOilk+dL3mUufckHKB8nlr3tTfpFVcn71WEBZSS4Vd3zVvkY81t6iWl0PWOXNZ6WogwqUsle3LWsSIANpP4uzjbhA992iqcKfnmuqoBRrqcz9VafYlA1uX4/iTcyZsYsCSGj/qQPphQEHNzEp8OblFNr6PPaetOiIt4A/YnnG1dFrP/tjJfKn4Y8UP42Q+X1Q+AgEfc3JN9fP8PZTnQHXL3xwV4+WUQh4huq6VpfiL2NKOIwtHc+7SjNSjdMYfQkoxkqcQtxLfngRj8jCgSmyWon/xw9wxVog5vDl7duYVpbvWhNoILYeBm/Q493wvdrsOnVuLE0rt4oNX1VXwCPNAfBo21FqJENOg+S/sDodmubpEeHQzseBl4/z8sBE7SxNIWTdi+IEwuO6NAxqEuhOB07Ipkpm4e/JC4TUKLE2v2w5irXRGtdedunY=
  on:
    branch: master
